create database storegames;
use storegames;



create table TB_USUARIO (

	ID_USUARIO		INT PRIMARY KEY AUTO_INCREMENT,
	NM_USUARIO		VARCHAR(100),
	DS_CEP			VARCHAR(12),
	DS_NASCIMENTO   DATE,
	DS_CPF			VARCHAR(14)
    
);

create table TB_ENDERECO (
    ID_ENDERECO              INT PRIMARY KEY AUTO_INCREMENT,
    DS_CEP                	 VARCHAR(9),
    DS_ENDERECO              VARCHAR(50),
    DS_CIDADE            	 VARCHAR(50),
    DS_BAIRRO                VARCHAR(50),
    DS_NUMERO                VARCHAR(6),
	FK_PEDIDO            	 INT,
    FOREIGN KEY (FK_PEDIDO) REFERENCES TB_PEDIDO (ID_PEDIDO)
);

create table TB_USUARIO_LOGIN (

	ID_USUARIO_LOGIN	INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO			INT,
	DS_EMAIL			VARCHAR(35),
	DS_SENHA			VARCHAR(30),
    FOREIGN KEY (ID_USUARIO)
    REFERENCES TB_USUARIO (ID_USUARIO)
    
);

create table TB_USUARIO_FAVORITO (
 ID_USUARIO_FAVORITO		INT PRIMARY KEY AUTO_INCREMENT,
 FK_USUARIO					INT,
 FK_JOGO					INT,
 
 FOREIGN KEY (FK_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO),
 FOREIGN KEY (FK_JOGO) REFERENCES TB_JOGO (ID_JOGO)

);

create table TB_ADMIN (

	ID_ADMIN 	INT PRIMARY KEY AUTO_INCREMENT,
	DS_NOME		VARCHAR(35)
    
);

create table TB_ADMIN_LOGIN (

	ID_ADMIN_LOGIN		INT PRIMARY KEY AUTO_INCREMENT,
    FK_ADMIN 			INT,
	DS_LOGIN			VARCHAR(35),
	DS_SENHA			VARCHAR(30),
	FOREIGN KEY (FK_ADMIN)
	REFERENCES TB_ADMIN (ID_ADMIN)
    
);


create table TB_JOGO (

	ID_JOGO				INT PRIMARY KEY AUTO_INCREMENT,
	NM_JOGO				VARCHAR(30),
	VL_JOGO				DECIMAL(10,2),
	DS_JOGO 			VARCHAR(500),
	QTD_ESTOQUE			INT,
    IMG_CAPA			VARCHAR(500),
	DS_REQUISITOS		VARCHAR(300),
    BL_DISPONIVEL		BOOLEAN,
	BL_MAISVENDIDO		BOOLEAN

);

create table TB_PEDIDO (
	ID_PEDIDO			INT PRIMARY KEY AUTO_INCREMENT,
    DS_STATUS			VARCHAR(50),
    VL_TOTAL			DECIMAL(10,2),
    VL_FRETE			DECIMAL(10,2),
    DT_PEDIDO			DATE
);

                    
create table TB_JOGO_PEDIDO (
	ID_JOGO_PEDIDO		INT PRIMARY KEY AUTO_INCREMENT,
    FK_PEDIDO			INT,
    FK_JOGO				INT,
	
    FOREIGN KEY (FK_PEDIDO)	
    REFERENCES TB_PEDIDO (ID_PEDIDO),
    
    FOREIGN KEY (FK_JOGO)
    REFERENCES TB_JOGO (ID_JOGO)
    
);

create table TB_PAGAMENTO_CARTAO (
	ID_PAGAMENTO_CARTAO		INT PRIMARY KEY AUTO_INCREMENT,
	NM_TITULAR_CARTAO		VARCHAR(50),
    DS_NUMERO_CARTAO		VARCHAR(20),
    DS_CPF					VARCHAR(12),
    DT_NASCIMENTO			DATE,
    DS_VALIDADE				VARCHAR(10),
    DS_CODVERIFICACAO		VARCHAR(5),
    QTD_PARCELAS			tinyint,
    FK_PEDIDO				INT,
	
    FOREIGN KEY (FK_PEDIDO)	REFERENCES TB_PEDIDO (ID_PEDIDO)
);

create table TB_PAGAMENTO_BOLETO (
	ID_PAGAMENTO_BOLETO			INT PRIMARY KEY AUTO_INCREMENT,
    NM_CLIENTE					VARCHAR(50),
    DS_EMAIL					VARCHAR(50),
    DS_CPF						VARCHAR(12),
    DS_TELEFONE					VARCHAR(12),
    FK_PEDIDO				INT,
    
    FOREIGN KEY (FK_PEDIDO) REFERENCES TB_PEDIDO (ID_PEDIDO)
    
);

create table TB_PAGAMENTO_PIX (
	ID_PAGAMENTO_PIX		INT PRIMARY KEY AUTO_INCREMENT,
    NM_CLIENTE				VARCHAR(50),
    DS_CPF					VARCHAR(12),
    FK_PEDIDO				INT,
    
    FOREIGN KEY (FK_PEDIDO) REFERENCES TB_PEDIDO (ID_PEDIDO)
);





create table TB_PLATAFORMA (

	ID_PLATAFORMA		INT PRIMARY KEY AUTO_INCREMENT,
	DS_PLATAFORMA		VARCHAR(30)
    
);

create table TB_GENERO (

	ID_GENERO		INT PRIMARY KEY AUTO_INCREMENT,
	DS_GENERO		VARCHAR(30)
    
);

create table TB_GENERO_JOGO (

	ID_GENERO_JOGO			INT PRIMARY KEY AUTO_INCREMENT,
    FK_JOGO					INT,
    FK_GENERO				INT,
    
    FOREIGN KEY (FK_JOGO)
    REFERENCES TB_JOGO (ID_JOGO),
    
    FOREIGN KEY (FK_GENERO)
    REFERENCES TB_GENERO (ID_GENERO)

);



create table TB_PLATAFORMA_JOGO (

	ID_PLATAFORMA_JOGO		INT PRIMARY KEY AUTO_INCREMENT,
    FK_JOGO					INT,
    FK_PLATAFORMA			INT,
   
    FOREIGN KEY (FK_JOGO)
    REFERENCES TB_JOGO (ID_JOGO),
    
    FOREIGN KEY (FK_PLATAFORMA)
    REFERENCES TB_PLATAFORMA (ID_PLATAFORMA)


);






