create database storegames;
use storegames;



create table TB_USUARIO (

	ID_USUARIO		INT PRIMARY KEY AUTO_INCREMENT,
	NM_USUARIO		VARCHAR(100),
	DS_CEP			VARCHAR(12),
	DS_NASCIMENTO   DATE,
	DS_CPF			VARCHAR(14)
    
);

create table TB_USUARIO_LOGIN (

	ID_USUARIO_LOGIN	INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO			INT,
	DS_EMAIL			VARCHAR(35),
	DS_SENHA			VARCHAR(30),
    FOREIGN KEY (ID_USUARIO)
    REFERENCES TB_USUARIO (ID_USUARIO)
    
);

create table TB_ADMIN (

	ID_ADMIN 	INT PRIMARY KEY AUTO_INCREMENT,
	DS_NOME		VARCHAR(35)
    
);

create table TB_ADMIN_LOGIN (

	ID_ADMIN_LOGIN		INT PRIMARY KEY AUTO_INCREMENT,
    FK_ADMIN 			INT,
	DS_LOGIN			VARCHAR(35),
	DS_SENHA			VARCHAR(30),
	FOREIGN KEY (FK_ADMIN)
	REFERENCES TB_ADMIN (ID_ADMIN)
    
);


create table TB_JOGO (

	ID_JOGO				INT PRIMARY KEY AUTO_INCREMENT,
	NM_JOGO				VARCHAR(30),
	VL_JOGO				DECIMAL(10,2),
	DS_JOGO 			VARCHAR(500),
	QTD_ESTOQUE			INT,
    IMG_CAPA			VARCHAR(30),
	DS_REQUISITOS		VARCHAR(300),
    BL_DISPONIVEL		BOOLEAN,
	BL_MAISVENDIDO		BOOLEAN

);




create table TB_PLATAFORMA (

	ID_PLATAFORMA		INT PRIMARY KEY AUTO_INCREMENT,
	DS_PLATAFORMA		VARCHAR(30)
    
);

create table TB_GENERO (

	ID_GENERO		INT PRIMARY KEY AUTO_INCREMENT,
	DS_GENERO		VARCHAR(30)
    
);

create table TB_GENERO_JOGO (

	ID_GENERO_JOGO			INT PRIMARY KEY AUTO_INCREMENT,
    FK_JOGO					INT,
    FK_GENERO				INT,
    
    FOREIGN KEY (FK_JOGO)
    REFERENCES TB_JOGO (ID_JOGO),
    
    FOREIGN KEY (FK_GENERO)
    REFERENCES TB_GENERO (ID_GENERO)

);



create table TB_PLATAFORMA_JOGO (

	ID_PLATAFORMA_JOGO		INT PRIMARY KEY AUTO_INCREMENT,
    FK_JOGO					INT,
    FK_PLATAFORMA			INT,
   
    FOREIGN KEY (FK_JOGO)
    REFERENCES TB_JOGO (ID_JOGO),
    
    FOREIGN KEY (FK_PLATAFORMA)
    REFERENCES TB_PLATAFORMA (ID_PLATAFORMA)


);






