create database storegames;
use storegames;

create table TB_USUARIO (
	ID_USUARIO		INT PRIMARY KEY AUTO_INCREMENT,
	NM_USUARIO		VARCHAR(100),
	DS_CEP			VARCHAR(12),
	DS_NASCIMENTO   DATE,
	DS_CPF			VARCHAR(14)
);

create table TB_USUARIO_LOGIN (
	ID_USUARIO_LOGIN	INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO			INT,
	DS_EMAIL			VARCHAR(35),
	DS_SENHA			VARCHAR(30),
    FOREIGN KEY (ID_USUARIO)
    REFERENCES TB_USUARIO (ID_USUARIO)
);

create table TB_ADMIN (
	ID_ADMIN 	INT PRIMARY KEY AUTO_INCREMENT,
	DS_NOME		VARCHAR(35)
);

create table TB_ADMIN_LOGIN (
	ID_ADMIN_LOGIN		INT PRIMARY KEY AUTO_INCREMENT,
    ID_ADMIN 			INT,
	DS_EMAIL			VARCHAR(35),
	DS_SENHA			VARCHAR(30),
	FOREIGN KEY (ID_ADMIN)
	REFERENCES TB_ADMIN (ID_ADMIN)
)




