use storegames;

INSERT INTO TB_ADMIN (DS_NOME)
	values ('Luan');
    INSERT INTO TB_ADMIN_LOGIN (FK_ADMIN, DS_LOGIN, DS_SENHA)
	values (1,'Luan', '1234');


-- CARGA INICIAL, AQUI TA INSERINDO OS GENEROS E PLATAFORMAS DOS JOGOS
-- TEM QUE INSERIR PELO MENOS CAMPO EM CADA UMA DAS TABELAS

insert into TB_GENERO (DS_GENERO)
				VALUES('Aventura');
                
insert into TB_GENERO (DS_GENERO)
				VALUES('Ação');
                
insert into TB_GENERO (DS_GENERO)
				VALUES('Casual');


insert into tb_plataforma (ds_plataforma)
					values('Ps4');
                    
insert into tb_plataforma (ds_plataforma)
					values('Xbox');	


insert into TB_JOGO (NM_JOGO, VL_JOGO, DS_JOGO, QTD_ESTOQUE, IMG_CAPA, DS_REQUISITOS, BL_DISPONIVEL, BL_MAISVENDIDO)
					values('MINECRAFT', 80.00, 'JOGO DE ACAO', 17, '',  'INTEL I5', TRUE, TRUE );
		

insert into TB_JOGO (NM_JOGO, VL_JOGO, DS_JOGO, QTD_ESTOQUE, IMG_CAPA,  DS_REQUISITOS, BL_DISPONIVEL, BL_MAISVENDIDO)
					values('GTA 5', 50.00, 'JOGO DE AVENTURA', 15, '',  'INTEL I5', TRUE, TRUE );



-- INSERIR GENERO NO JOGO
INSERT INTO TB_GENERO_JOGO (FK_JOGO, FK_GENERO)
					 VALUES(1, 1);

-- INSERIR PLATAFORMA NO JOGO
INSERT INTO TB_PLATAFORMA_JOGO (FK_JOGO, FK_PLATAFORMA)
					     VALUES(1, 1);


-- VISUALIZA O JOGO COM O GENERO 
SELECT * 
FROM TB_JOGO AS J
INNER JOIN TB_GENERO_JOGO AS GJ 
ON GJ.FK_JOGO = J.ID_JOGO
INNER JOIN TB_GENERO AS G
ON G.ID_GENERO = GJ.FK_GENERO;

-- VISUALIZA O JOGO COM A PLATAFORMA 
SELECT *
FROM TB_JOGO AS J
INNER JOIN TB_PLATAFORMA_JOGO AS PJ 
ON PJ.FK_JOGO = J.ID_JOGO
INNER JOIN TB_PLATAFORMA AS P
ON P.ID_PLATAFORMA = PJ.FK_PLATAFORMA;

-- SELECT MALUCO
SELECT 
	JOG.ID_JOGO, JOG.NM_JOGO, CAT.DS_GENERO, PLAT.DS_PLATAFORMA
FROM TB_JOGO AS JOG
LEFT JOIN TB_GENERO_JOGO AS GJ ON GJ.FK_JOGO = JOG.ID_JOGO
LEFT JOIN TB_PLATAFORMA_JOGO AS PJG ON PJG.FK_JOGO = JOG.ID_JOGO
LEFT JOIN TB_GENERO AS CAT ON CAT.ID_GENERO = GJ.FK_GENERO
LEFT JOIN TB_PLATAFORMA AS PLAT ON PLAT.ID_PLATAFORMA = PJG.FK_PLATAFORMA
ORDER BY JOG.ID_JOGO;